//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 05:24:07 PM IST 
//


package com.ground.fedex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Location"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="doorId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="doorType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Location", propOrder = {
    "doorId",
    "doorType"
})
public class Location {

    protected int doorId;
    @XmlElement(required = true)
    protected String doorType;

    /**
     * Gets the value of the doorId property.
     * 
     */
    public int getDoorId() {
        return doorId;
    }

    /**
     * Sets the value of the doorId property.
     * 
     */
    public void setDoorId(int value) {
        this.doorId = value;
    }

    /**
     * Gets the value of the doorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoorType() {
        return doorType;
    }

    /**
     * Sets the value of the doorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoorType(String value) {
        this.doorType = value;
    }

}
